import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}

/**
 * Config provider theme - hashed: false
 * This allow to override ant design classes otherwise will show the following class components
 * "css-dev-only-do-not-override"
 * Ref: https://github.com/ant-design/ant-design/issues/41926
 */
